# Site settings
title: Eye Robot
email: sn3ae@berkeley.edu
url: https://snarain.github.io
description: "Envisioning whole new worlds"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Eye Robot

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/gsambhav/capstone-ssm 

# Build settings
markdown: kramdown
permalink: pretty
